version: '3.4'
services:
  app-db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      # not recommended
      - POSTGRES_HOST_AUTH_METHOD=trust
  app:
    build: .
    ports:
      - '8080:8080'
    tty: true
    stdin_open: true