version: "2.1"

services:
  db:
    container_name: db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      # not recommended
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    build: .
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    tty: true
    stdin_open: true